#!/usr/bin/env bash
#
# measure_flash.sh — per-scheme flash/RAM footprint by delta build.
#
#   bash scripts/measure_flash.sh pico
#   bash scripts/measure_flash.sh esp32
#
# METHOD
# ------
# Absolute ELF size is not a per-scheme number: it includes the SDK, the USB
# stack, mbedTLS and the harness, none of which are attributable to any one
# algorithm. So we build a BASELINE with every RUN_* switched off, then one
# build per scheme with only that scheme on, and report the DELTA:
#
#     footprint(scheme) = size(baseline + scheme) - size(baseline)
#
# That delta is the marginal cost of adding the scheme to a firmware image,
# which is the figure a deployment engineer actually needs. It is reported as
# text (flash, code+rodata), data (flash-backed initialised RAM) and bss
# (zero-initialised RAM) separately, because .text is the flash cost while
# data+bss is the static RAM cost — they trade off differently on a 264 KB part.
#
# Note this measures STATIC footprint only. Peak stack is measured separately by
# the firmware itself (see BENCH_STACK in the harness) and is not included here.
#
# The script edits bench_config.h in place and restores it on exit, including on
# Ctrl-C or build failure.
set -euo pipefail

PLATFORM="${1:-}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCHEMES=(MLKEM MLDSA ECDSA FALCON SPHINCS)
OUT="$ROOT/results/tables/flash_${PLATFORM}.md"

case "$PLATFORM" in
  pico)
    CONFIG="$ROOT/pico/src/bench_config.h"
    BUILD="$ROOT/pico/build"
    ELF="$BUILD/bench_pico.elf"
    SIZE="${SIZE_TOOL:-arm-none-eabi-size}"
    do_build() {
      rm -rf "$BUILD"
      cmake -S "$ROOT/pico" -B "$BUILD" \
            -DCMAKE_C_COMPILER="$(which arm-none-eabi-gcc)" \
            -DCMAKE_CXX_COMPILER="$(which arm-none-eabi-g++)" >/dev/null
      cmake --build "$BUILD" --target bench_pico -j"$(sysctl -n hw.ncpu 2>/dev/null || nproc)" >/dev/null
    }
    ;;
  esp32)
    CONFIG="$ROOT/esp32/main/bench_config.h"
    ELF="$ROOT/esp32/build/pqc_bench_esp32.elf"
    SIZE="${SIZE_TOOL:-xtensa-esp32-elf-size}"
    do_build() { ( cd "$ROOT/esp32" && idf.py build >/dev/null ); }
    ;;
  *)
    echo "usage: $0 {pico|esp32}" >&2; exit 2 ;;
esac

[ -f "$CONFIG" ] || { echo "no config at $CONFIG" >&2; exit 1; }
command -v "$SIZE" >/dev/null || {
  echo "'$SIZE' not on PATH. Set SIZE_TOOL=... to override." >&2; exit 1; }
if [ "$PLATFORM" = pico ] && [ -z "${PICO_SDK_PATH:-}" ]; then
  echo "PICO_SDK_PATH is not set." >&2; exit 1
fi

BACKUP="$(mktemp)"
cp "$CONFIG" "$BACKUP"
trap 'cp "$BACKUP" "$CONFIG"; rm -f "$BACKUP"; echo; echo "bench_config.h restored."' EXIT

set_scheme() {  # $1 = scheme to enable, or "none"
  cp "$BACKUP" "$CONFIG"
  local s val
  for s in "${SCHEMES[@]}"; do
    val=0; [ "$s" = "${1:-none}" ] && val=1
    # portable in-place sed (BSD sed on macOS needs the empty -i argument)
    sed -i '' -E "s/^#define[[:space:]]+RUN_${s}[[:space:]]+[01]/#define RUN_${s}    ${val}/" \
      "$CONFIG" 2>/dev/null || \
    sed -i -E "s/^#define[[:space:]]+RUN_${s}[[:space:]]+[01]/#define RUN_${s}    ${val}/" \
      "$CONFIG"
  done
}

read_size() {  # echoes "text data bss"
  "$SIZE" "$ELF" | awk 'NR==2 {print $1, $2, $3}'
}

echo "Platform: $PLATFORM"
echo "Baseline build (all schemes off)..."
set_scheme none
do_build
read -r B_TEXT B_DATA B_BSS <<<"$(read_size)"
echo "  baseline: text=$B_TEXT data=$B_DATA bss=$B_BSS"

mkdir -p "$(dirname "$OUT")"
{
  echo "# Per-scheme static footprint — $PLATFORM"
  echo
  echo "Delta against a baseline firmware with every scheme disabled."
  echo "Baseline: text=$B_TEXT data=$B_DATA bss=$B_BSS bytes."
  echo "text = flash (code+rodata); data+bss = static RAM. Peak stack is measured"
  echo "separately by the firmware and is NOT included here."
  echo
  echo "| Scheme | Δ text (flash, B) | Δ data (B) | Δ bss (B) | Δ flash total (KB) |"
  echo "|---|--:|--:|--:|--:|"
} > "$OUT"

for s in "${SCHEMES[@]}"; do
  echo "Building $s..."
  set_scheme "$s"
  if ! do_build; then
    echo "  BUILD FAILED for $s — skipping" >&2
    echo "| $s | build failed | — | — | — |" >> "$OUT"
    continue
  fi
  read -r T D BS <<<"$(read_size)"
  dt=$((T - B_TEXT)); dd=$((D - B_DATA)); db=$((BS - B_BSS))
  kb=$(awk -v a="$dt" -v b="$dd" 'BEGIN{printf "%.1f", (a+b)/1024}')
  printf '  %-8s text +%-8d data +%-6d bss +%-8d (%s KB flash)\n' "$s" "$dt" "$dd" "$db" "$kb"
  echo "| $s | $dt | $dd | $db | $kb |" >> "$OUT"
done

echo >> "$OUT"
echo "Generated by \`scripts/measure_flash.sh $PLATFORM\` on $(date -u +%Y-%m-%d)." >> "$OUT"
echo
echo "Wrote $OUT"
